language: php

php:
   - 7.2
   - 7.3
   - 7.4

services:
   - memcached

env:
   - PECL_MEMCACHE=memcache-3.0.9

before_script:
   - yes "" | pecl install -f "$PECL_MEMCACHE"
   # Need to activate memchached extension explictly to work with all versions.
   - phpenv config-add .travis-php.ini;
   - composer self-update || true
   # Ensure the memcache extension is available
   - composer show --platform ext-memcache
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
